set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256

set showmode
"命令行显示vim当前模式

set showcmd
"命令行显示输入的命令
set relativenumber
"set rnu	relativeline
set colorcolumn=84
"显示红竖
set smartindent
"智能对齐方式
set tabstop=5
"tab键个数
set background=dark
"背景颜色

syntax on
"语法高亮度显示
filetype on                    
"检测文件的类型  
