set laststatus=2
"开启状态横幅
set t_Co=256
"设置256色位(maybe)

set showmode
"命令行显示vim当前模式

set showcmd
"命令行显示输入的命令
set colorcolumn=84
"显示红竖
set smartindent
"智能对齐方式
set tabstop=5
"tab键个数
set background=dark
"背景颜色

syntax on
"语法高亮度显示
filetype on                    
"检测文件的类型  

set fileencodings=uft-8,gbk "使用utf-8或gbk打开文件
set cursorline              "为光标所在行加下划线
